spring.application.name=webellian-task

# Connection string
spring.datasource.url=jdbc:sqlite:safehaven.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate/JPA Configuration for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL queries in the console for easy debugging
spring.jpa.show-sql=true
