spring.application.name=webellian-task

# Connection URL (with persistent .db file)
# Uncomment below for persistent storage
# spring.datasource.url=jdbc:sqlite:safehaven.db
# spring.datasource.driver-class-name=org.sqlite.JDBC

# Connection URL using in-memory mode with shared cache
# Uncomment below for in memory database (volatile)
spring.datasource.url=jdbc:sqlite:file::memory:?cache=shared
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.pool-name=SQLitePool
spring.datasource.hikari.maximum-pool-size=1


# Hibernate/JPA Configuration for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL queries in the console for easy debugging
spring.jpa.show-sql=true
